server:
  port: 8086
  servlet:
    context-path: /api/plumemo-service
spring:
  profiles:
    active: dev
  datasource:
    name: plumemo
    url:  ${MYSQL_DATABASE:jdbc:mysql://127.0.0.1:3306/plumemo?useSSL=false&characterEncoding=utf8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: plumemo
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB  #设置支持的单个上传文件大小
      max-request-size: 6MB  #设置最大的请求文件大小，设置总体大小的请求
      file-size-threshold: 512KB #当上传文件达到指定配置量的时候，会将文件内容写入到磁盘
      location: /   #设置上传文件的临时目录

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  typeAliasesPackage: com.byteblogs.plumemo.*.dao
  global-config:
    db-config:
      #数据库大写下划线转换
      capital-mode: false
      #删除
      logic-delete-value: 1
      #不删除
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  config: classpath:config/spring-logback.xml
